# Generated by Django 4.2 on 2023-04-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0002_fileupload_file_name_fileupload_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
