# Generated by Django 4.2 on 2023-04-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrappy', '0003_alter_fileupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='channels/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('file_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='playlists/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('file_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
